Update backends.py
The "ImportError: cannot import name 'force_text' from 'django.utils.encoding'" error occurs when a package or module tries to import the force_text function from Django's encoding module, but the function has been removed and replaced with force_str in Django version 4.